name: Workflow

on:
  push:
    branches:
      - feature-clase1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        
      - name: Build with Gradle (if Maven fails)
        if: failure()
        run: ./gradlew build -x test